{{- define "common.configmap" -}}
  {{- if or .Values.configmap .Values.global.elasticApm }}
apiVersion: v1
kind: ConfigMap
  {{- include "common.metadata" . }}
data:
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.global.elasticApm }}
  {{- range $key, $value := .Values.global.elasticApm}}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- range .Values.configmapMounts }}
  {{- if .data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  {{- include "common.selectorLabels" $ | nindent 4 }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}

{{- end }}