{{- define "common.secret" -}}
  {{- $common := dict "Values" .Values.common -}}
  {{- $noCommon := omit .Values "common" -}}
  {{- $overrides := dict "Values" $noCommon -}}
  {{- $noValues := omit . "Values" -}}
  {{- with merge $noValues $overrides $common -}}
  {{- range .Values.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" $ }}-{{ .name }}
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  {{- include "common.selectorLabels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}